name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: brew install hub
    - name: Build
      run: |
        yarn install
        yarn build
    - name: Release
      run: hub release create -p -m "Dev Build / ${GITHUB_SHA}" -a web/dist/strata.js "v0.1-${GITHUB_SHA:0:7}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
