name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Tests
      run: xcodebuild -project Strada.xcodeproj -scheme Strada -quiet test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.3.app
